### ISSUE TITLE
fetchey 기본기능

### ISSUE THREAD

**Issue by jangwonyoon** [jangwonyoon/fetchey#1]
## todo

- [x] get
  - [x] 기본 url 호출
  - [x] 타입정의
  - [ ] 테스트 진행
- [x] post
  - [x] 기본 Url 호출
  - [x] 타입정의
  - [ ] 테스트 진행
- [x] put
  - [x] 기본 Url 호출
  - [x] 타입정의
  - [ ] 테스트 진행
- [x] Delete
  - [x] 기본 Url 호출
  - [x] 타입정의
  - [ ] 테스트 진행
